name: boring_counter
description: Boring counter for you to count things
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  bloc: ^8.1.2
  dio: ^5.4.0
  dio_smart_retry: ^6.0.0
  firebase_analytics: ^10.8.1
  firebase_core: ^2.25.0
  firebase_crashlytics: ^3.4.10
  firebase_performance: ^0.9.3+8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  injectable: ^2.3.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  mockito: ^5.4.4
  pretty_dio_logger: ^1.3.1
  responsive_builder: ^0.7.0
  retrofit: ^4.0.3
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  uuid: ^4.3.3

dev_dependencies:
  auto_route_generator: ^7.3.2
  bloc_test: ^9.1.5
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  injectable_generator: ^2.4.1
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  retrofit_generator: ^8.0.6
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
