name: boring_counter
description: Boring counter for you to count things
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  auto_route: ^5.0.4
  bloc: ^8.1.1
  dio: ^5.0.2
  dio_smart_retry: ^5.0.0
  firebase_analytics: ^10.1.5
  firebase_core: ^2.7.1
  firebase_crashlytics: ^3.0.16
  firebase_performance: ^0.9.0+15
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.8.0
  logger: ^1.3.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1
  rxdart: ^0.27.7
  uuid: ^3.0.7

dev_dependencies:
  auto_route_generator: ^5.0.3
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  freezed: ^2.3.2
  injectable_generator: ^2.1.4
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  retrofit_generator: ^6.0.0+1
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
