jobs:
  - job: Web_Build_Check
    pool:
      vmImage: 'macOS-latest'
    variables:
      - group: boring-counter-firebase
      - name: flavor
        value: 'development'
    steps:

      - task: FlutterInstall@0
        displayName: 'Install Flutter'
        inputs:
          mode: 'auto'
          channel: 'stable'
          version: 'custom'
          customVersion: '3.7.7'

      - task: Bash@3
        displayName: 'Build Web App'
        inputs:
          targetType: 'inline'
          script: |
            $(FLUTTERTOOLPATH)/flutter build web -t lib/main_$(flavor).dart

      - task: Bash@3
        displayName: 'Deploy preview'
        inputs:
          targetType: 'inline'
          script: |
            npm i -g firebase-tools
            DEPLOY_RESULT=$(firebase hosting:channel:deploy $(Build.SourceVersion) \
              --token $(FIREBASE_TOKEN))
            echo "$DEPLOY_RESULT"
            HOSTING_LINE=$(echo "$DEPLOY_RESULT" | grep -ie "hosting:channel:\ Channel URL")
            echo "Hosting line:\ $HOSTING_LINE"
            echo "##vso[task.setvariable variable=hostingline;]$HOSTING_LINE"

      - powershell: |
          $body = @"
          {
            "comments": [
              {
                "parentCommentId": 0,
                "content": "You can preview web version of the App at\n$(hostingline)",
                "commentType": 1
              }
            ],
            "status": 4
            }
          "@
          $url = "$($env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI)$env:SYSTEM_TEAMPROJECTID/_apis/git/repositories/$($env:BUILD_REPOSITORY_NAME)/pullRequests/$($env:SYSTEM_PULLREQUEST_PULLREQUESTID)/threads?api-version=5.1"
          $result = Invoke-RestMethod -Uri $url -Method POST -Headers @{Authorization = "Bearer $(System.AccessToken)"} -Body $Body -ContentType application/json
        displayName: Post comment on PR
