name: Generate coverage badge

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, review_requested]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter_channel: stable
          flutter_version: 3.16.5
      - name: Restore packages
        run: flutter pub get
      - name: Run tests
        run: flutter test --coverage

      - name: Use Node.js 14.19.1
        uses: actions/setup-node@v4
        with:
          node-version: 14.19.1
      - run: yarn install
      - run: yarn generate_coverage_badge

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "chore: Updated code coverage badge"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }}